# -*- coding: utf-8 -*-
"""my_area_functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z82PFTjp9Dg9ypGoI94UPIlK5DnPyhi3
"""

triangle_area = lambda b, h: ...

triangle_area = lambda b, h: 0.5*b*h

def triangle_area (b, h):
  """ Compute the area of a right triangle.

  Args.
      b - the base length of the triangle.
      h - the height of the triangle.

  Returns.  The area of the triangle (a number)
  """
  area = 0.5*b*h
  return area

def test_triangle_area():
  assert triangle_area(0, 1) == 0
  assert triangle_area(1, 0) == 0
  assert triangle_area(4, 1) == 2
  assert triangle_area(1, 4) == 2
  assert triangle_area(4, 2) == 4
  assert triangle_area(2, 4) == 4
  assert triangle_area(4.5, 2.4) == 0.5*4.5*2.4
test_triangle_area()